// src/data/shoppingDealsData.js

export const trendingShopping = [
  {
    id: 1,
    name: "Noise Smartwatch",
    image: "https://picsum.photos/300/200?random=11",
    rating: 4.6,
    oldPrice: 2999,
    newPrice: 1999,
    category: "Wearables",
  },
  {
    id: 2,
    name: "Adidas Running Shoes",
    image: "https://picsum.photos/300/200?random=12",
    rating: 4.8,
    oldPrice: 4999,
    newPrice: 3499,
    category: "Footwear",
  },
  {
    id: 3,
    name: "Mi Power Bank 10000mAh",
    image: "https://picsum.photos/300/200?random=13",
    rating: 4.5,
    oldPrice: 1299,
    newPrice: 999,
    category: "Electronics",
  },
  {
    id: 4,
    name: "T-shirt Combo Pack",
    image: "https://picsum.photos/300/200?random=14",
    rating: 4.3,
    oldPrice: 1199,
    newPrice: 799,
    category: "Fashion",
  },
];

export const cheapestShopping = [
  {
    id: 1,
    name: "USB Type-C Cable",
    image: "https://picsum.photos/300/200?random=15",
    rating: 4.2,
    oldPrice: 299,
    newPrice: 149,
    category: "Accessories",
  },
  {
    id: 2,
    name: "Plain Cotton Socks (Pack of 3)",
    image: "https://picsum.photos/300/200?random=16",
    rating: 4.0,
    oldPrice: 199,
    newPrice: 99,
    category: "Fashion",
  },
  {
    id: 3,
    name: "Toothbrush Set",
    image: "https://picsum.photos/300/200?random=17",
    rating: 3.9,
    oldPrice: 149,
    newPrice: 89,
    category: "Essentials",
  },
  {
    id: 4,
    name: "Keychain Combo",
    image: "https://picsum.photos/300/200?random=18",
    rating: 4.1,
    oldPrice: 199,
    newPrice: 99,
    category: "Lifestyle",
  },
];

export const bestDealsShopping = [
  {
    id: 1,
    name: "JBL Bluetooth Speaker",
    image: "https://picsum.photos/300/200?random=19",
    rating: 4.9,
    oldPrice: 4999,
    newPrice: 2999,
    category: "Audio",
    discount: "40% OFF",
  },
  {
    id: 2,
    name: "Lenovo Wireless Mouse",
    image: "https://picsum.photos/300/200?random=20",
    rating: 4.7,
    oldPrice: 899,
    newPrice: 499,
    category: "Accessories",
    discount: "45% OFF",
  },
  {
    id: 3,
    name: "Roadster Denim Jacket",
    image: "https://picsum.photos/300/200?random=21",
    rating: 4.6,
    oldPrice: 2499,
    newPrice: 1499,
    category: "Fashion",
    discount: "35% OFF",
  },
  {
    id: 4,
    name: "Philips Hair Dryer",
    image: "https://picsum.photos/300/200?random=22",
    rating: 4.5,
    oldPrice: 1999,
    newPrice: 1299,
    category: "Personal Care",
    discount: "30% OFF",
  },
];
